### ISSUE TITLE
ATS v1.49 Crashes on startup/sdk reload

### ISSUE THREAD

**Issue by BeyBladey** [dariowouters/ts-fmod-plugin#22]
Hi.
Game crashes after editing "selected.bank.txt" and doing a **sdk reload** on console, or simply after loading the profile once .txt is edited (it crashes on loading screen).

On thing i noticed on "game.log.txt" (under the same release, v1.49) is that ETS2 says this:

> 00:00:26.605 : **[ts-fmod-plugin V1.49]** Searching for memory offsets... If this is one of the last messages in the log after a crash, try disabling this plugin after choosing profile.
> 00:00:26.616 : [ts-fmod-plugin] Found base_ctrl @ 1d079a0 and unk_interior @1d07998
> 00:00:26.718 : [ts-fmod-plugin] Found output device[0] Altavoces (Realtek(R) Audio)
> 00:00:26.718 : [ts-fmod-plugin] Found output device[1] Realtek Digital Output (Realtek(R) Audio)
> 00:00:26.718 : [ts-fmod-plugin] Found output device[2] VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO)
> 00:00:26.719 : [ts-fmod-plugin] Found output device[3] 1 - LG IPS FULLHD (AMD High Definition Audio Device)
> 00:00:26.719 : [ts-fmod-plugin] Found output device[4] VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)
> 00:00:26.719 : [ts-fmod-plugin] Selecting default output device (0)
> 00:00:26.888 : [ts-fmod-plugin] Using sound bank[0]: 'rckps_v8op'
> 00:00:26.888 : [ts-fmod-plugin] Loading the events and busses for 'rckps_v8op'
> 00:00:26.909 : [ts-fmod-plugin] Loading event 'engine/engine'
> 00:00:26.909 : [ts-fmod-plugin] Loading event 'engine/exhaust'
> 00:00:26.909 : [ts-fmod-plugin] Loading event 'engine/start_bad'
> 00:00:26.909 : [ts-fmod-plugin] Loading event 'engine/turbo'
> 00:00:26.909 : <WARNING> [ts-fmod-plugin] Did not find any navigation event. You will not have navigation voices.
> 00:00:26.926 : [ts-fmod-plugin] Plugin loaded

_Note: ETS2 works fine, that's after selecting a .bank_

...while on the ATS "game.log.txt" says:

> 00:03:14.009 : **[ts-fmod-plugin V1.46]** Searching for economy offset... If this is one of the last messages in the log after a crash, try disabling this plugin.
> 00:03:14.031 : [ts-fmod-plugin] Found economy offset &1d04528
> 00:03:14.144 : [ts-fmod-plugin] Found output device[0] Altavoces (Realtek(R) Audio)
> 00:03:14.144 : [ts-fmod-plugin] Found output device[1] Realtek Digital Output (Realtek(R) Audio)
> 00:03:14.145 : [ts-fmod-plugin] Found output device[2] VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO)
> 00:03:14.145 : [ts-fmod-plugin] Found output device[3] 1 - LG IPS FULLHD (AMD High Definition Audio Device)
> 00:03:14.145 : [ts-fmod-plugin] Found output device[4] VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)
> 00:03:14.145 : [ts-fmod-plugin] Selecting default output device (0)
> 00:03:14.267 : [ts-fmod-plugin] Using sound bank[0]: '903_v8'
> 00:03:14.267 : [ts-fmod-plugin] Loading the events and busses for '903_v8'
> 00:03:14.284 : [ts-fmod-plugin] Setting sound level for 'master' to 0.5
> 00:03:14.284 : [ts-fmod-plugin] Setting sound level for 'engine' to 0.5
> 00:03:14.284 : [ts-fmod-plugin] Setting sound level for 'exhaust' to 0.5
> 00:03:14.284 : [ts-fmod-plugin] Setting sound level for 'turbo' to 0.5
> 00:03:14.284 : [ts-fmod-plugin] Setting sound level for 'interior' to 1
> 00:03:14.284 : [ts-fmod-plugin] Setting sound level for 'exterior_when_windows_closed' to 0.75
> 00:03:14.284 : [ts-fmod-plugin] Plugin loaded

If i'm missing something or need anything for further debug, please let me know.
Have a nice day/night!

**Comment by Baldywaldy09** [comment]
the problem is because your using plugin version: 1.46 on ATS 
and on ETS2 your using 1.49

you need to update your ATS plugin to 1.49

**Comment by Baldywaldy09** [comment]
You didn't update the ats dll
As on the 1st line of the log in ATS u can see it says a different version then 1.49

**Comment by Baldywaldy09** [comment]
Ets2 and ATS both use the same dll file

**Comment by BeyBladey** [comment]
Smh what a dumb issue i opened... sry
